// app/layout.js
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "../../components/Providers";
import { WebSocketProvider } from "./contexts/WebSocketContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <WebSocketProvider>
          {children}
          </WebSocketProvider>
        </Providers>
      </body>
    </html>
  );
}
